# Generated by Django 3.2.8 on 2021-10-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='finished',
            field=models.BooleanField(),
        ),
    ]
